name: emailtamer
services:
  db:
    container_name: app-local-db
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 3306:3306
  localstack-s3:
    image: localstack/localstack:latest
    container_name: app-localstack-s3
    environment:
      - SERVICES=s3
    ports:
      - "4566-4584:4566-4584"
      - "8080:8080"
    volumes:
      - app-localstack-data:/var/lib/localstack

volumes:
  app-localstack-data:
    name: app-localstack-data