// <auto-generated />
using System;
using EmailTamer.Database.Tenant;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailTamer.Database.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250408144644_AddThreadIdToMessages")]
    partial class AddThreadIdToMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmailBoxMessage", b =>
                {
                    b.Property<Guid>("EmailBoxesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessagesId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("EmailBoxesId", "MessagesId");

                    b.HasIndex("MessagesId");

                    b.ToTable("EmailBoxMessage");
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.EmailBox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("AuthenticateByEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BoxName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailDomainConnectionHost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmailDomainConnectionPort")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UseSSl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "ModifiedAt");

                    b.ToTable("EmailBoxes", t =>
                        {
                            t.HasCheckConstraint("CHK_EmailBoxes_IdNotDefault", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Folders", t =>
                        {
                            t.HasCheckConstraint("CHK_Folders_IdNotDefault", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AttachmentFilesNames")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InReplyTo")
                        .HasColumnType("longtext");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResentDate")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("TextBody")
                        .HasColumnType("longtext");

                    b.Property<string>("ThreadId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("FolderMessage", b =>
                {
                    b.Property<Guid>("FoldersId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessagesId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("FoldersId", "MessagesId");

                    b.HasIndex("MessagesId");

                    b.ToTable("FolderMessage");
                });

            modelBuilder.Entity("EmailBoxMessage", b =>
                {
                    b.HasOne("EmailTamer.Database.Tenant.Entities.EmailBox", null)
                        .WithMany()
                        .HasForeignKey("EmailBoxesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmailTamer.Database.Tenant.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FolderMessage", b =>
                {
                    b.HasOne("EmailTamer.Database.Tenant.Entities.Folder", null)
                        .WithMany()
                        .HasForeignKey("FoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmailTamer.Database.Tenant.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
