// <auto-generated />
using System;
using EmailTamer.Database.Tenant;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailTamer.Database.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250208123309_AddMessagesTable")]
    partial class AddMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.EmailBox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("AuthenticateByEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BoxName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailDomainConnectionHost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmailDomainConnectionPort")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UseSSl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "ModifiedAt");

                    b.ToTable("EmailBoxes", t =>
                        {
                            t.HasCheckConstraint("CHK_EmailBoxes_IdNotDefault", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("EmailBoxId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Folders")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InReplyTo")
                        .HasColumnType("longtext");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResentDate")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME");

                    b.Property<string>("S3FolderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("TextBody")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmailBoxId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.Message", b =>
                {
                    b.HasOne("EmailTamer.Database.Tenant.Entities.EmailBox", "EmailBox")
                        .WithMany("Messages")
                        .HasForeignKey("EmailBoxId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("EmailBox");
                });

            modelBuilder.Entity("EmailTamer.Database.Tenant.Entities.EmailBox", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
